graph TB
    Root[GPTK LMS Project]
    
    Root --> P1[1. Initiation &<br/>Requirements]
    Root --> P2[2. Design &<br/>Architecture]
    Root --> P3[3. Backend<br/>Development]
    Root --> P4[4. Database<br/>Implementation]
    Root --> P5[5. Frontend<br/>Development]
    Root --> P6[6. Integration<br/>& Testing]
    Root --> P7[7. Documentation]
    Root --> P8[8. Deployment &<br/>Submission]
